name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Install flatpak-builder
      run: sudo -S apt install  flatpak-builder -y
    - uses: actions/checkout@v4
    - name: Build and run tests
      run: ./flatpak_test.sh
