name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Update
      run: sudo apt-get update -y
    - name: Install flatpak
      run: sudo apt install flatpak -y
    - name: Install flatpak-builder
      run: sudo apt install flatpak-builder -y
    - uses: actions/checkout@v4
    - name: Build flatpak app
      run: flatpak-builder flatpak_build io.github.aganzha.Stage-tests.json --force-clean
    - name: Build and run tests
      run: flatpak-builder --run flatpak_build io.github.aganzha.Stage-tests.json ./flatpak_test.sh
