name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Install gtk4
      run: sudo -S apt install libgtk-4-dev -y
    - name: Intall libadwaita
      run: sudo -S apt install libadwaita-1-dev -y
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: ./test.sh
