name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Install flatpak
      run: sudo -S apt install flatpak -y
    - name: Install flatpak-builder
      run: sudo -S apt install flatpak-builder -y
    - name: Add flathub to remotes
      run: flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: Install Gnome runtime
      run: sudo flatpak install --system -y org.gnome.Sdk/x86_64/47
    - name: Install Rust extension
      run: sudo flatpak install --system -y org.freedesktop.Sdk.Extension.rust-stable/x86_64/24.08
    - uses: actions/checkout@v4
    - name: Build and run tests
      run: ./flatpak_test.sh
