name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Update
      run: sudo apt-get update -y
    - name: Install build tools
      run: sudo apt install build-essential -y
    - name: Install gtk
      run: sudo apt install libgtk-4-dev -y
    - name: Install libadwaita
      run: sudo apt install libadwaita-1-dev -y
    - name: Install libssl
      run: sudo apt-get install libssl-dev -y
    - uses: actions/checkout@v4
    - name: Build and run tests
      run: ./tests.sh
      working-directory: /home/runner/work/stage/stage/
